# Generated by Django 5.1.6 on 2026-06-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_pro_categor_0d8ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-id'], name='product_pro_id_4d417c_idx'),
        ),
    ]
